// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5lR1GEczy74a0g2oExspxf5g7lsHx4Q',
    appId: '1:849967201601:web:87f96b28675147174535c0',
    messagingSenderId: '849967201601',
    projectId: 'clicks-outlet',
    authDomain: 'clicks-outlet.firebaseapp.com',
    storageBucket: 'clicks-outlet.appspot.com',
    measurementId: 'G-DS8CGV7PM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcmvQ_NecyxCbDd_PA3pVghn2TpXx_1T4',
    appId: '1:849967201601:android:da837d99178714a84535c0',
    messagingSenderId: '849967201601',
    projectId: 'clicks-outlet',
    storageBucket: 'clicks-outlet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtl-bt3ZLIozNRAmKHKezmUU5BE9alJYM',
    appId: '1:849967201601:ios:2bce6d47e06aaa5e4535c0',
    messagingSenderId: '849967201601',
    projectId: 'clicks-outlet',
    storageBucket: 'clicks-outlet.appspot.com',
    iosBundleId: 'com.example.async.it.clicksoutlet',
  );
}
