// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5lR1GEczy74a0g2oExspxf5g7lsHx4Q',
    appId: '1:849967201601:web:9430fb093b5facf44535c0',
    messagingSenderId: '849967201601',
    projectId: 'clicks-outlet',
    authDomain: 'clicks-outlet.firebaseapp.com',
    storageBucket: 'clicks-outlet.appspot.com',
    measurementId: 'G-C63JK9LVMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcmvQ_NecyxCbDd_PA3pVghn2TpXx_1T4',
    appId: '1:849967201601:android:65cdc7d451a136804535c0',
    messagingSenderId: '849967201601',
    projectId: 'clicks-outlet',
    storageBucket: 'clicks-outlet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtl-bt3ZLIozNRAmKHKezmUU5BE9alJYM',
    appId: '1:849967201601:ios:574e764c5ff5aba34535c0',
    messagingSenderId: '849967201601',
    projectId: 'clicks-outlet',
    storageBucket: 'clicks-outlet.appspot.com',
    androidClientId: '849967201601-cjg1d1s537i6ugp6pmm8jda7ndc2fn4t.apps.googleusercontent.com',
    iosClientId: '849967201601-qm49olbep7dsbn14ovg9jilvd1q1d7j1.apps.googleusercontent.com',
    iosBundleId: 'com.async.it.clicksoutlet.clicksOutlet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtl-bt3ZLIozNRAmKHKezmUU5BE9alJYM',
    appId: '1:849967201601:ios:574e764c5ff5aba34535c0',
    messagingSenderId: '849967201601',
    projectId: 'clicks-outlet',
    storageBucket: 'clicks-outlet.appspot.com',
    androidClientId: '849967201601-cjg1d1s537i6ugp6pmm8jda7ndc2fn4t.apps.googleusercontent.com',
    iosClientId: '849967201601-qm49olbep7dsbn14ovg9jilvd1q1d7j1.apps.googleusercontent.com',
    iosBundleId: 'com.async.it.clicksoutlet.clicksOutlet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ5lR1GEczy74a0g2oExspxf5g7lsHx4Q',
    appId: '1:849967201601:web:ea4b6eeca588b59d4535c0',
    messagingSenderId: '849967201601',
    projectId: 'clicks-outlet',
    authDomain: 'clicks-outlet.firebaseapp.com',
    storageBucket: 'clicks-outlet.appspot.com',
    measurementId: 'G-Y3PT00LBWZ',
  );

}